# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e12036637e4c0adfdb2d3ecd9183456a45b31578bd5454c5e68efb5d62c8bc9e8b41277a21b32bbad4253099ac33c5c49bc3988bab236a72866ddcf38a4d1f5

test:
  secret_key_base: a47273aef4d05c46330dbfa1d752eb5a824bce0efbadde5a7a249df1afc944847d4571148339c9c1756b949d7a75a0002a924ac42942c5eaf220004e5ba2edec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
